name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version: '3.11'

      - name: Cache venv directory
        uses: actions/cache@v2
        with:
          path: .boston_house_price_prediction_venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m venv .boston_house_price_prediction_venv
          source .boston_house_price_prediction_venv/bin/activate
          echo "******************** Created Python Virtual Environment ********************"
          python -m pip install -r requirements.txt
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Run tests
        run: |
          # Replace this line with the command to run your tests
          pytest --cov=src src/tests/boston_housing_price_prediction/test_*.py
